name: Build and Test

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Test Image
        run: docker build -t client-cs:latest -f ./dockerfile.test .
      - name: Run Test Image
        run: docker run --rm client-cs:latest
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            GITHUB_WORKFLOW	${{github.workflow}}
            GITHUB_ACTION	${{github.action}}
            GITHUB_EVENT_NAME	${{github.event.name}}
            GITHUB_EVENT_PATH	${{github.event.path}}
            GITHUB_WORKSPACE	${{github.workspace}}

            The ${{ github.event_name }} event triggered second step.
            show the github variable ref: ${{ github.ref }}
            show the github variable commit: ${{ github.sha }}
            Commit Message: ${{ github.event.head_commit.message }}
