name: Build and Test

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Test Image
        run: docker build -t client-cs:latest -f ./dockerfile.test .
      - name: Run Test Image
        run: docker run --rm client-cs:latest
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            <strong> ${{github.workflow}} </strong>

            <code> repository: ${{ github.repository }} </code>

            <code> user: ${{ github.actor }} </code>

            <code> commit: ${{ github.event.head_commit.message }} </code>
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
